#!/bin/bash
ACTION_DIR="./.github-release-matrix-action"
rm -rf "$ACTION_DIR"
mkdir -p "$ACTION_DIR"

export RUNNER_TEMP="${ACTION_DIR}/tmp"
mkdir -p "$RUNNER_TEMP"
export GITHUB_OUTPUT="${ACTION_DIR}/GITHUB_OUTPUT"
export GITHUB_ENV="${ACTION_DIR}/GITHUB_ENV"
touch "$GITHUB_OUTPUT"
touch "$GITHUB_ENV"

INPUT_REPOSITORY=${1:$INPUT_REPOSITORY}
INPUT_RELEASE=${2:-${INPUT_RELEASE:-"*"}}
INPUT_PRERELEASE=${3:-${INPUT_PRERELEASE:-"false"}}
INPUT_PREFIX=${4:-${INPUT_PREFIX:-"false"}}
INPUT_LIMIT=${5:-${INPUT_LIMIT:-"3"}}

./action.sh "${INPUT_REPOSITORY}" "${INPUT_RELEASE}" "${INPUT_PRERELEASE}" "${INPUT_PREFIX}" "${INPUT_LIMIT}" "${INPUT_POST_RUN_COMMANDS}"
